### ISSUE TITLE
Viber wrong size  

### ISSUE THREAD

**Issue by ivonenchev** [flathub/com.viber.Viber#84] opened 2024-02-18 08:29 UTC
When I have tried to install Viber via following command : 

flatpak install flathub  com.viber.Viber, 

I have faced error below : 

  1. [✗] com.viber.Viber         stable         i          flathub         153,3 MB / 156,9 MB

Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

**Comment by akurtakov** [comment] 2024-02-19 10:41
Duplicate of https://github.com/flathub/com.viber.Viber/issues/79

**Closed by akurtakov** 2024-02-19 10:41 UTC
