### ISSUE TITLE
viber not installing

### ISSUE THREAD

**Issue by legacychimera247** [flathub/com.viber.Viber#1] opened 2017-10-25 15:50 UTC
tried to install viber out of curiosity but unfortunately the app is not installing...neither in store or cmd...this is the cmd output

`Installing: com.viber.Viber/x86_64/stable
Installing: com.viber.Viber/x86_64/stable from flathub
[######################] Downloading: 106,3 MB/93,3 MB (1,1 MB/s)  
error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb` 

i am using fedora 26 if needed...

**Comment by nedrichards** [comment] 2017-10-25 16:09
Apologies, viber released a new version, although it should still be smaller than 106.3 MB. Anyway, this should be fixed by https://github.com/flathub/com.viber.Viber/commit/e37e52402027a0808e3a4b0ff7c5d12c9074e484 which is being automatically rebuilt even as we speak. If that doesn't fix it do let me know.

**Closed by nedrichards** 2017-10-25 16:09 UTC

**Comment by lilicenco** [comment] 2019-03-16 19:36
Hello, as of 03/03/2019
produces such a message. for two days I can not install
error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
Thanks

**Comment by mkrajnak** [comment] 2019-03-22 14:48
The issue is still present for me today:

![image](https://user-images.githubusercontent.com/10319675/54831017-dce27480-4cb9-11e9-9dd9-c4df14b89024.png)

**Comment by yaroslaw-mashko** [comment] 2019-03-26 13:10
26.03.2019
Error message. Wrong size for extra data ...

**Comment by stojadin** [comment] 2019-03-27 15:19
I'm experiencing the same issue

**Comment by nedrichards** [comment] 2019-03-28 16:31
Should be fixed by https://github.com/flathub/com.viber.Viber/commit/a40ae1d019ef075ea9e5bd85534fdb844734a1a0

**Comment by user216** [comment] 2019-03-28 18:15
the same issue 

flatpak install '/sysroot/home/andrii/Downloads/com.viber.Viber (1).flatpakref' 
Installing in system:
com.viber.Viber/x86_64/stable flathub 7645126cc6fd
  permissions: ipc, network, pulseaudio, x11, devices
  file access: xdg-desktop, xdg-documents, xdg-download, xdg-pictures, xdg-videos, ~/.ViberPC:create
  dbus access: org.freedesktop.Notifications, org.kde.StatusNotifierWatcher
Is this ok [y/n]: y
Installing: com.viber.Viber/x86_64/stable from flathub
[#################-  ] Downloading files: 53/53 87.1 MB (1.4 MB/s)              
error: Failed to install com.viber.Viber/x86_64/stable: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb


endless os

**Comment by ineedausername** [comment] 2020-07-15 15:07
Hello.  

Getting the error again right now:

Error: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
error: Failed to install com.viber.Viber: Wrong size for extra data https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb

Installing the flathub version since the one from the .deb file stopped sending outgoing messages to contacts.  I can type the messages, but they dont get sent.
